### PR TITLE
Add alternative way for custom TextProvider

### PR DESCRIPTION
**Pull request by Tal-Daniel**
Added [in comments] alternative way to extend Struts 2 TextProvider that seems simpler & faster to develop. It skips the need to extend TextProviderFactory.

### CODE REVIEW

**Comment by lukaszlenart** [comment]
LGTM 👍  - thanks!

**Comment by Tal-Daniel** [comment]
Lukas, today I found out that my suggestion comments work for v2.5.10.1, but not for v2.5.13.
I suggest to revert the merge request, if you can. Sorry about that, but code do change :)

**Comment by lukaszlenart** [comment]
Hmm... but maybe we can put it back ;-) I mean that overriding only the TextProvider would be possible again :)

**Comment by lukaszlenart** [comment]
https://github.com/apache/struts/pull/178

**Pull request merged**
